### PR TITLE
#65: Adding Support for Alerts to serenity-js

### PR DESCRIPTION
**Pull request by nbarrett**
feat: support for alerts accept and cancel (not able to run specs yet due to unexplained run-time errors

### CODE REVIEW

**Comment by nbarrett** [comment]
Hey @jan-molak - I'm having a spot of bother with getting `npm run verify` to work, so need a little advice if that's okay? I'm on `node --version -> v6.9.5`
But in amongst quite a few other errors, I'm getting:

```
serenity-js ERROR src/serenity-protractor/screenplay/abilities/browse_the_web.ts (73,22): Argument of type '() => void' is not assignable to parameter of type '() => PromiseLike<{}>'.\n  Type 'void' is not assignable to type 'PromiseLike<{}>'. (2345)\n    at getOutput (/Users/nick/dev/git-personal/serenity-js/node_modules/ts-node/src/index.ts:319:17)\n    at /Users/nick/dev/git-personal/serenity-js/node_modules/ts-node/src/index.ts:350:18\n    at Object.compile (/Users/nick/dev/git-personal/serenity-js/node_modules/ts-node/src/index.ts:483:19)\n    at Object.m._compile (/Users/nick/dev/git-personal/serenity-js/node_modules/ts-node/src/index.ts:413:44)\n    at Module._extensions..js (module.js:579:10)\n    at Object.require.extensions.(anonymous function) [as .ts] (/Users/nick/dev/git-personal/serenity-js/node_modules/ts-node/src/index.ts:416:12)\n    at NYC._readTranspiledSource (/Users/nick/dev/git-personal/serenity-js/node_modules/nyc/index.js:160:26)\n    at NYC.addFile (/Users/nick/dev/git-personal/serenity-js/node_modules/nyc/index.js:144:21)\n    at /Users/nick/dev/git-personal/serenity-js/node_modules/nyc/index.js:176:11\n    at /Users/nick/dev/git-personal/serenity-js/node_modules/nyc/index.js:244:5
```

**Comment by nbarrett** [comment]
Morning @jan-molak! After a long pause, I'm turning my attention towards getting this PR finished and refreshing my memory about things. First of all, I'm trying to get a clean build of serenity-js master by running ``npm run verify`` but I'm having trouble getting a clean build as I see these kinds of failures:
```
58 passing (2m)
lerna ERR! execute   4 failing
lerna ERR! execute 
lerna ERR! execute   1) When waiting for things to happen, a test scenario using Active Wait (setTimeout) to determine if an element is not present in the DOM will pass if the condition is met within the timeout:
lerna ERR! execute      Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
lerna ERR! execute   
lerna ERR! execute 
lerna ERR! execute   2) When waiting for things to happen, a test scenario using Active Wait (setTimeout) to determine if an element is clickable will pass if the condition is met within the timeout:
lerna ERR! execute      Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
lerna ERR! execute   
lerna ERR! execute 
lerna ERR! execute   3) When waiting for things to happen, a test scenario using Active Wait ($timeout) to determine if an element is not present in the DOM will pass if the condition is met within the timeout:
lerna ERR! execute      Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
lerna ERR! execute   
lerna ERR! execute 
lerna ERR! execute   4) When waiting for things to happen, a test scenario using Active Wait ($interval) to determine if an element is invisible will pass if the condition is met within the timeout:
lerna ERR! execute      Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
lerna ERR! execute   
lerna ERR! execute 
lerna ERR! execute 
```

I have a basic problem of wanting to look at the test reports to see what failed but when I run

`npm run report` I seem to only get the istanbul coverage reports, not the serenity reports - what am I doing wrong please?

**Comment by nbarrett** [comment]
Hi @jan-molak - I've made some further progress and have rebased and pushed latest changes to my branch with dd3509f. To get over the problem of the whole suite not running reliably for me, I've been running just the cookbook suite. I also renamed my spec packages/serenity-js/spec/cookbook/waiting.recipe.ts and it now seems to be running.
using the following commands:
```
cd packages/serenity-js
npm run spec:cookbook
```
However, I'm finding that after the first of my scenarios where an alert gets triggered, the web app gets left in a hung state and all following scenarios timeout I wonder whether this is due to a shift of window focus away from the browser window to a process called `GridLauncher`. Any suggestions on way forward welcomed please!

**Comment by nbarrett** [comment]
I've made some further changes last night and when I run `npm run spec:cookbook` I can see the alert accept scenario working but the alert cancel scenario fails and then causes all further scenarios to fail. This would imply that the step
```
 after(app.stop());
```
is not closing the web app down fully. I'll have to stop work on this now @jan-molak until you have a look as it's failing in areas that I'm not clear how to progress on. Also the travis builds are failing at the pull request command step which again is outside my area of knowledge....

**Comment by nbarrett** [comment]
This is the cancelAlert implementation that causes the whole test suite to get stuck:

```
    cancelAlert(): PromiseLike<void> {
        return this.browser.getTitle().then(title => this.browser.switchTo().alert().cancel());
    }
```

I've also tried this:
```
    cancelAlert(): PromiseLike<void> {
        return this.browser.getTitle().then(title => this.browser.switchTo().alert().dismiss());
    }
```

But it makes no difference. In all cases the screen freezes with this:

image

**Comment by jan-molak** [comment]
Interesting, why do we need to call `getTitle` by the way?

**Comment by nbarrett** [comment]
Heyyy @jan-molak - welcome to this PR! I used that to create  promise in order to turn the `void` into a `PromiseLike<void>`. I know I should probably have used `defer()` but just couldn't work out the magic...Very much looking for some molak-magic on this one!

**Comment by nbarrett** [comment]
Hold on.... I got it working!

a) Just realised that alert().dismiss() already returns a `PromiseLike<void>`, so no need to do the `this.browser.getTitle().then(` promise trick
b) `this.browser.switchTo().alert().dismiss())` IS the thing that clicks cancel (no idea why protractor team did it that way).

w00t - My PR works!! (Travis build still broken though I think)

**Comment by nbarrett** [comment]
Thanks 🙌  Jan for comments. All good. I'll push those changes tonight and then we'll take it from there!

**Pull request merged**
